"""empty message

Revision ID: 707983673260
Revises: c0c0aba38ab1
Create Date: 2021-02-22 11:30:42.892129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707983673260'
down_revision = 'c0c0aba38ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=150), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('is_editing', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_due_date'), 'todo', ['due_date'], unique=False)
    op.drop_index('ix_toDO_due_date', table_name='toDO')
    op.drop_table('toDO')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toDO',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=True),
    sa.Column('body', sa.VARCHAR(length=150), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('is_complete', sa.BOOLEAN(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('is_complete IN (0, 1)'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_toDO_due_date', 'toDO', ['due_date'], unique=False)
    op.drop_index(op.f('ix_todo_due_date'), table_name='todo')
    op.drop_table('todo')
    # ### end Alembic commands ###
